### ISSUE TITLE
Yaml Support

### ISSUE THREAD

**Issue by BrutalSimplicity** [MacHu-GWU/cottonformation-project#3]
It looks like `template.to_yml` is not implemented. Are there plans to support this?

Awesome library by the way. Exactly what I've been looking for!

**Comment by MacHu-GWU** [comment]
Yes I think that should be easy to support, I will release a new version with this feature in 1 week. Thank you for your feedback

**Comment by BrutalSimplicity** [comment]
I see you've already merged the update to `master`. Many Thanks!

One suggestion from looking at the code (as I was trying to assist with a PR) is that you're using the `cfn_flip` to convert the json to yaml, which should work; but, I think you can avoid the json serialization and have `cfn_flip` dump the yaml directly with the `cfn_flip.dump_yaml` function.

Do you think that's worth an update?

**Comment by MacHu-GWU** [comment]
@BrutalSimplicity  from performance perspective, it doesn't worth to. the `cfn_flip. dump_yaml` requires a dictionary object. But cottonformation dictionary object may not be exactly match the desired format, I would say it is more stable to dump to json, then convert to yaml.

**Comment by BrutalSimplicity** [comment]
It's not really about performance, but ensuring that the underlying dictionary implementation is respected. You should have no problem swapping your dictionary implementation as I believe it inherits from `dict` (or maybe `OrderedDict`, which also inherits from `dict`).

Right now, you can't be sure what the underlying implementation of `cfn_flip.to_yaml` will do to a json string as it's an implementation detail of the library. For example, you don't know if it will respect the order of the json dictionary and/or lists. If you use a function that operates directly on the dictionary implementation I'd think you have a greater chance of respecting its behavior.

**Comment by MacHu-GWU** [comment]
I am little bit got your points, could you provide me an example that will break if convert dict -> json -> yml?

**Comment by MacHu-GWU** [comment]
@BrutalSimplicity if it doesn't bother you anymore, I would like to close this issue in 7 days.
